Change dir-mount to copy-in for the completion tests' images.
redhat-developer/helm-acceptance-testing pull request #3
Opened 2020-05-29 09:41 UTC by pmacik

2020-06-02 07:29 UTC, pratikjagrut commented
/lgtm

2020-06-02 07:29 UTC, pratikjagrut commented
LGTM

2020-06-02 09:13 UTC, bamachrn commented
rather than building a new container each time can't we use volume from? in that way we build the image only once.

2020-06-09 14:42 UTC, pedjak commented
@bamachrn I think we cannot use volumes, because we do not have a way to copy files from container to the volume. I mean the files are created during container execution. The volume should be mounted for this container first and created before the script gets executed.

2020-06-10 09:58 UTC, bamachrn commented
@pedjak My idea was we build a container with the completion code and mount it from other built containers. If the files are getting created in execution it self then it make sense to put them in the container itself.

2020-06-10 16:20 UTC, pedjak requested changes
please squash comits and add PR description to the commit message as well. Then we are going to be ready for the upstream as well.

2020-06-11 10:31 UTC, merged